### ISSUE TITLE
installation of Fractal has no CSS

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-eleventy#1]
running `gulp dev` fires up a browser with `localhost:3000` which gives a basic fractal install of the components.

It does not load the CSS - looking at it I think the `fractal.js` isn't running / working / added. 

I have done something similar before - but making use of 'fractal inside fractal' so it's slightly different - but happy to share the codes.

**Comment by khawkins98** [comment]
Suspicion is that this is an order-of-operation issues with the browser opening before the CSS has been built. Will look into it.

**Comment by khawkins98** [comment]
This should behave better now ... namely in that it doesn't show the pattern library browser tab on `gulp dev`.  It's probably confusing.

**Comment by khawkins98** [comment]
I think this one is sorted now. Closing
