### ISSUE TITLE
localhost:8080 doesn't open in the browser

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-eleventy#2]
It'd be nice if, when running, the actual site opens in a new browser tab

**Comment by khawkins98** [comment]
The option to open a new tab when 11ty runs is hardcoded, but I don't think it would be hard to change. 

https://github.com/11ty/eleventy/blob/master/src/EleventyServe.js#L69

Might open a ticket with 11ty, or maybe even make a PR...

**Comment by khawkins98** [comment]
Sorted now. 

There was a config parameter I had a hard time finding:

`config.setBrowserSyncConfig({ open: true });`

https://github.com/visual-framework/vf-eleventy/blob/master/eleventy.js#L18
