### ISSUE TITLE
app.css doesn't get pushed into build folder

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-eleventy#5]
using vf-eleventy as a clone for embl-communications/design-system it seems that any changes I make to app.scss does not get pushed into the build folder or recognised.

**Comment by sturobson** [comment]
Actually - it looks like it builds on `gulp dev` but there's no watch task to see if there's anything changed.

**Comment by khawkins98** [comment]
Think this one's sorted now, closing.
